-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.appointments
(
    id serial NOT NULL,
    student_id integer NOT NULL,
    student_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    doctor_id integer NOT NULL,
    doctor_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    "time" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'scheduled'::character varying,
    reason text COLLATE pg_catalog."default",
    CONSTRAINT appointments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.concerns
(
    id serial NOT NULL,
    student_id integer NOT NULL,
    category character varying(255) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    response text COLLATE pg_catalog."default",
    responded_by integer,
    responded_at timestamp without time zone,
    CONSTRAINT concerns_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.doctor_availability
(
    id serial NOT NULL,
    doctor_id integer NOT NULL,
    date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    max_patients integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT doctor_availability_pkey PRIMARY KEY (id),
    CONSTRAINT doctor_availability_doctor_id_date_start_time_end_time_key UNIQUE (doctor_id, date, start_time, end_time)
);

CREATE TABLE IF NOT EXISTS public.medicines
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    stock integer DEFAULT 0,
    price integer DEFAULT 0,
    CONSTRAINT medicines_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_medicines
(
    order_id integer NOT NULL,
    medicine_id integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT order_medicines_pkey PRIMARY KEY (order_id, medicine_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id serial NOT NULL,
    student_id integer NOT NULL,
    student_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    ordered_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    total integer DEFAULT 0,
    prescription_link text COLLATE pg_catalog."default",
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prescriptions
(
    id serial NOT NULL,
    student_id integer NOT NULL,
    doctor_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date date DEFAULT CURRENT_DATE,
    medicines text COLLATE pg_catalog."default",
    diagnosis text COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    category character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT prescriptions_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.prescriptions.category
    IS 'Indicates if prescription is general or specialized';

CREATE TABLE IF NOT EXISTS public.referrals
(
    id serial NOT NULL,
    student_id integer NOT NULL,
    student_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    requested_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    doctor_notes text COLLATE pg_catalog."default",
    CONSTRAINT referrals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    roll_number character varying(50) COLLATE pg_catalog."default",
    specialization character varying(255) COLLATE pg_catalog."default",
    time_per_patient integer,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_doctor_id_fkey FOREIGN KEY (doctor_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.concerns
    ADD CONSTRAINT concerns_responded_by_fkey FOREIGN KEY (responded_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.concerns
    ADD CONSTRAINT concerns_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_concerns_student_id
    ON public.concerns(student_id);


ALTER TABLE IF EXISTS public.doctor_availability
    ADD CONSTRAINT doctor_availability_doctor_id_fkey FOREIGN KEY (doctor_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_notifications_user_id
    ON public.notifications(user_id);


ALTER TABLE IF EXISTS public.order_medicines
    ADD CONSTRAINT order_medicines_medicine_id_fkey FOREIGN KEY (medicine_id)
    REFERENCES public.medicines (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_medicines
    ADD CONSTRAINT order_medicines_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.prescriptions
    ADD CONSTRAINT prescriptions_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.referrals
    ADD CONSTRAINT referrals_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;